team : 
    type: rest
    prefix: /v1
    resource:     'Pouce\TeamBundle\Controller\TeamController'
    name_prefix:  api_1_

position :
    type: rest
    prefix: /v1
    resource:     'Pouce\TeamBundle\Controller\PositionController'
    name_prefix:  api_1_