users: 
    type: rest
    prefix: /v1
    resource: 'Pouce\UserBundle\Controller\UserController'
    name_prefix: api_1_ # naming collision

schools: 
    type: rest
    prefix: /v1
    resource: 'Pouce\UserBundle\Controller\SchoolController'
    name_prefix: api_1_ # naming collision